spring.application.name=pharmasn
spring.datasource.url=jdbc:postgresql://localhost:5433/pharmasn
spring.datasource.username=abdoul
spring.datasource.password=abdoul
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
app.jwt.secret=change-this-to-a-long-random-secret-key-for-dev-only-123456789
app.jwt.expiration-ms=86400000
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

